"""Fresh assembly comparison with unchanged labels and an oracle-route diagnostic."""
import json
import os
from pathlib import Path
import tempfile
import time
from datetime import datetime, timezone
from collections import Counter


def main():
    with tempfile.TemporaryDirectory(prefix="migtorg-answer-") as temp:
        os.environ.update(DATABASE_PATH=str(Path(temp) / "eval.sqlite3"), LLM_ENABLED="false",
            LLM_UNDERSTANDING_ENABLED="false", TICKET_EMAIL_ENABLED="false", INTERNAL_STATUS_API_ENABLED="false",
            ROUTING_ARCHITECTURE="control", DIALOGUE_STATE_ENABLED="true", ANSWER_ASSEMBLY_ENABLED="false",
            ARCHITECTURE_EXPERIMENT="true", HF_HUB_OFFLINE="1", TRANSFORMERS_OFFLINE="1",
            SEMANTIC_MODEL_ALLOW_DOWNLOAD="false", OMP_NUM_THREADS="1", MKL_NUM_THREADS="1")
        from backend.app import main as app
        from backend.app.bot import knowledge_search as ks
        from backend.app.bot.answer_generator import generate_answer
        from backend.app.models.chat import ChatRequest
        from backend.app.build_manifest import build_runtime_manifest
        from backend.tools.evaluate_live_queries import load_dataset, evaluate_response
        from backend.tools.evaluate_architecture import metrics
        from fastapi.testclient import TestClient
        dataset, cases = load_dataset(Path("tests/data/routing_v3_closed_control_270.json"),
                                     Path("tests/data/routing_label_adjudication_110.json"))
        ks.warm_knowledge_indexes()
        report = {"schema_version": 1, "generated_at": datetime.now(timezone.utc).isoformat(),
            "fresh_runtime": True, "assessment": "automatic scenario/resolution/marker checks, not expert semantic acceptance",
            "release_allowed": False, "dataset_sha256": dataset["sha256"], "adjudication": dataset["adjudication"], "variants": {}}
        details = {}
        client = TestClient(app.app)
        for enabled in (False, True):
            name = "assembly_on" if enabled else "assembly_off"
            app.settings.answer_assembly_enabled = enabled
            manifest = build_runtime_manifest(app.settings)
            rows, oracle, parity, profiles = [], [], [], Counter()
            for i,case in enumerate(cases):
                started = time.perf_counter()
                response = app.process_chat_message(ChatRequest(message=case["text"], session_id=f"{name}-{i}"))
                row = evaluate_response(case, response.model_dump(), (time.perf_counter()-started)*1000,
                    global_forbidden=dataset.get("global_forbidden_answer_fragments", []))
                with app.logger._connect() as conn:
                    trace = json.loads(conn.execute("SELECT trace_json FROM decision_traces WHERE message_id = ?", (response.message_id,)).fetchone()[0])
                row["trace"] = trace
                rows.append(row)
                profile = trace.get("answer_plan", {}).get("profile")
                if profile:
                    profiles[profile] += 1
                # Every assembled route plus a fixed periodic sample exercises HTTP.
                if profile and profile != "published_template" or i % 20 == 0:
                    result = client.post("/api/chat/message", json={"message": case["text"], "session_id": f"http-{name}-{i}"})
                    if result.status_code != 200 or any(result.json().get(k) != response.model_dump().get(k)
                        for k in ("answer", "scenario_id", "resolution", "actions", "template_links", "action_result")):
                        parity.append(case["id"])
                article = next((a for sid in case["expected"].get("expected_scenario_ids", [])
                                if sid and (a := ks.get_article_by_id(sid,"guest"))), None)
                if article:
                    answer = generate_answer(case["text"], article.intent, "guest", article, False, settings=app.settings)
                    # Oracle diagnostic assesses answer text only; resolution is not generated by this layer.
                    from copy import deepcopy
                    answer_case = deepcopy(case)
                    for key in ("allowed_resolutions", "expect_direct", "expected_intents"):
                        answer_case["expected"].pop(key, None)
                    result = evaluate_response(answer_case, {"scenario_id": article.scenario, "intent": article.intent,
                        "answer": answer.answer, "resolution": "answered"}, 0,
                        global_forbidden=dataset.get("global_forbidden_answer_fragments", []))
                    result["verification_reason"] = answer.verification_reason
                    oracle.append(result)
                if (i+1) % 50 == 0:
                    print(f"{name}: {i+1}/{len(cases)}", flush=True)
            details[name] = {"runtime": rows, "oracle_text_only": oracle}
            routed = [r for r in rows if r["checks"]["route_hit"]]
            report["variants"][name] = {"manifest": manifest, "runtime": metrics(rows),
                "correct_route_answer_checks": {"passed": sum(r["checks"]["answer_hit"] for r in routed), "total": len(routed)},
                "oracle_text_checks": {"passed": sum(r["checks"]["answer_hit"] for r in oracle), "total": len(oracle)},
                "profiles": dict(profiles), "http_parity_failures": parity}
            print(name, json.dumps({k:v for k,v in report["variants"][name].items() if k!='manifest'},ensure_ascii=False),flush=True)
        for population in ("runtime", "oracle_text_only"):
            report[population + "_changes"] = [{"id": a["id"], "before": a["checks"]["answer_hit"], "after": b["checks"]["answer_hit"],
                "before_answer": a["response"]["answer"], "after_answer": b["response"]["answer"], "after_diagnostics": b["diagnostics"]}
                for a,b in zip(details["assembly_off"][population],details["assembly_on"][population])
                if a["response"]["answer"] != b["response"]["answer"]]
        ending = build_runtime_manifest(app.settings)
        report["bundle_unchanged"] = all(ending[k]==report["variants"]["assembly_off"]["manifest"][k]
            for k in ("application_bundle_sha256","knowledge_sha256","policy_bundle_sha256","evaluator_sha256"))
        Path("reports/answer-assembly-evaluation.json").write_text(json.dumps(report,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
        Path(".work/answer-assembly-details.json").write_text(json.dumps(details,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")


if __name__ == "__main__":
    main()
